version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mypostgres
      POSTGRES_USER: mypostgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mypostgres
      DB_USER: mypostgres
      DB_PASSWORD: mypassword
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data:
